/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import db.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public Login() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelMainFrame = new javax.swing.JPanel();
                jPanelLoginFrame = new javax.swing.JPanel();
                jTextUserName = new javax.swing.JTextField();
                jPasswordField = new javax.swing.JPasswordField();
                jSeparatorUserName = new javax.swing.JSeparator();
                jSeparatorPassword = new javax.swing.JSeparator();
                jLabelUserNameIcon = new javax.swing.JLabel();
                jLabelPasswordIcon = new javax.swing.JLabel();
                jLabelInvisible = new javax.swing.JLabel();
                jLabelVisible = new javax.swing.JLabel();
                jButtonLogIn = new javax.swing.JButton();
                jButtonCancel = new javax.swing.JButton();
                jLabelStudentManagement = new javax.swing.JLabel();
                jLabelLogo = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowOpened(java.awt.event.WindowEvent evt) {
                                formWindowOpened(evt);
                        }
                });

                jPanelMainFrame.setBackground(new java.awt.Color(255, 255, 255));

                jPanelLoginFrame.setBackground(new java.awt.Color(255, 102, 102));
                jPanelLoginFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jTextUserName.setBackground(new java.awt.Color(255, 102, 102));
                jTextUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
                jTextUserName.setForeground(new java.awt.Color(51, 51, 51));
                jTextUserName.setText("User Name");
                jTextUserName.setBorder(null);
                jTextUserName.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTextUserNameMouseClicked(evt);
                        }
                });
                jPanelLoginFrame.add(jTextUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 185, 20));

                jPasswordField.setBackground(new java.awt.Color(255, 102, 102));
                jPasswordField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
                jPasswordField.setForeground(new java.awt.Color(51, 51, 51));
                jPasswordField.setText("Password");
                jPasswordField.setBorder(null);
                jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jPasswordFieldMouseClicked(evt);
                        }
                });
                jPanelLoginFrame.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 185, 20));

                jSeparatorUserName.setBackground(new java.awt.Color(51, 51, 51));
                jSeparatorUserName.setForeground(new java.awt.Color(0, 0, 0));
                jPanelLoginFrame.add(jSeparatorUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 185, 10));

                jSeparatorPassword.setBackground(new java.awt.Color(51, 51, 51));
                jSeparatorPassword.setForeground(new java.awt.Color(0, 0, 0));
                jPanelLoginFrame.add(jSeparatorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 185, 10));

                jLabelUserNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user for userName.png"))); // NOI18N
                jPanelLoginFrame.add(jLabelUserNameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

                jLabelPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock for password.png"))); // NOI18N
                jPanelLoginFrame.add(jLabelPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 26));

                jLabelInvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Invisible.png"))); // NOI18N
                jLabelInvisible.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelInvisibleMouseClicked(evt);
                        }
                });
                jPanelLoginFrame.add(jLabelInvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 20, 20));

                jLabelVisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Visible.png"))); // NOI18N
                jLabelVisible.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelVisibleMouseClicked(evt);
                        }
                });
                jPanelLoginFrame.add(jLabelVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 20, 20));

                jButtonLogIn.setBackground(new java.awt.Color(51, 51, 51));
                jButtonLogIn.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
                jButtonLogIn.setForeground(new java.awt.Color(255, 255, 255));
                jButtonLogIn.setText("Log In");
                jButtonLogIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonLogInActionPerformed(evt);
                        }
                });
                jPanelLoginFrame.add(jButtonLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 80, 30));

                jButtonCancel.setBackground(new java.awt.Color(51, 51, 51));
                jButtonCancel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
                jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
                jButtonCancel.setText("Exit");
                jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCancelActionPerformed(evt);
                        }
                });
                jPanelLoginFrame.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 80, 30));

                jLabelStudentManagement.setBackground(new java.awt.Color(51, 51, 51));
                jLabelStudentManagement.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
                jLabelStudentManagement.setForeground(new java.awt.Color(51, 51, 51));
                jLabelStudentManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelStudentManagement.setText("Student Management");
                jPanelLoginFrame.add(jLabelStudentManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 290, -1));

                jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/smallLogoplaceHolder.jpg"))); // NOI18N

                javax.swing.GroupLayout jPanelMainFrameLayout = new javax.swing.GroupLayout(jPanelMainFrame);
                jPanelMainFrame.setLayout(jPanelMainFrameLayout);
                jPanelMainFrameLayout.setHorizontalGroup(
                        jPanelMainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMainFrameLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanelLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanelMainFrameLayout.setVerticalGroup(
                        jPanelMainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelLoginFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                        .addGroup(jPanelMainFrameLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabelLogo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

	int xx,xy;
        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                for (double i = 0.1; i <= 1.0; i += 0.1) {
			String s = i + "";
			float f = Float.valueOf(s);
			this.setOpacity(f);
			try {
				Thread.sleep(40);
			} catch (InterruptedException ex) {
				Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
        }//GEN-LAST:event_formWindowOpened

        private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
                System.exit(0);
        }//GEN-LAST:event_jButtonCancelActionPerformed

        private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
                if(isEmpty()) {
                        Connection con = MyConnection.getConnection();
                        PreparedStatement ps;

                        String username = jTextUserName.getText();
                        String password = String.valueOf(jPasswordField.getPassword());
                        try {
                                ps = con.prepareStatement("select * from admin where username = ? and password = ?");
                                ps.setString(1, username);
                                ps.setString(2, password);
                                ResultSet rs = ps.executeQuery();
                                if (rs.next()) {
                                        JOptionPane.showMessageDialog(this, "Log in Successful");
                                        Home home = new Home();
                                        home.setVisible(true);
                                        home.pack();
                                        this.dispose();
                                } else {
                                        JOptionPane.showMessageDialog(this, "Invalid User name or Password");

                                }
                        } catch (SQLException ex) {
                                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }//GEN-LAST:event_jButtonLogInActionPerformed

        private void jLabelVisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVisibleMouseClicked
                jPasswordField.setEchoChar('*');
                jLabelInvisible.setVisible(true);
                jLabelVisible.setVisible(false);
        }//GEN-LAST:event_jLabelVisibleMouseClicked

        private void jLabelInvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInvisibleMouseClicked
                jPasswordField.setEchoChar((char) 0);
                jLabelInvisible.setVisible(false);
                jLabelVisible.setVisible(true);
        }//GEN-LAST:event_jLabelInvisibleMouseClicked

        private void jPasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMouseClicked
                jPasswordField.setText("");
        }//GEN-LAST:event_jPasswordFieldMouseClicked

        private void jTextUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUserNameMouseClicked
                jTextUserName.setText("");
        }//GEN-LAST:event_jTextUserNameMouseClicked

	public boolean isEmpty() {
		if(jTextUserName.getText().isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please enter user name");
			return false;
		}if (String.valueOf(jPasswordField.getPassword()).isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please enter password");
			return false;
		}
		return true;
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
				jLabelVisible.setVisible(false);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonCancel;
        private javax.swing.JButton jButtonLogIn;
        private javax.swing.JLabel jLabelInvisible;
        private javax.swing.JLabel jLabelLogo;
        private javax.swing.JLabel jLabelPasswordIcon;
        private javax.swing.JLabel jLabelStudentManagement;
        private javax.swing.JLabel jLabelUserNameIcon;
        private static javax.swing.JLabel jLabelVisible;
        private javax.swing.JPanel jPanelLoginFrame;
        private javax.swing.JPanel jPanelMainFrame;
        private javax.swing.JPasswordField jPasswordField;
        private javax.swing.JSeparator jSeparatorPassword;
        private javax.swing.JSeparator jSeparatorUserName;
        private javax.swing.JTextField jTextUserName;
        // End of variables declaration//GEN-END:variables
}
